add td500 dataset convert
mindspore-lab/mindocr pull request #248
Opened 2023-04-28 09:46 UTC by Songyuanwei

Thank you for your contribution to the MindOCR repo.
Before submitting this PR, please make sure:

- [ ] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests

## Motivation

(Write your motivation for proposed changes here.)

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

2023-04-28 13:15 UTC, SamitHuang approved these changes

2023-04-30 14:59 UTC, wtomin requested changes
1. Please provide TD500 download instructions as mindocr/docs/en/datasets/td500.md and mindocr/docs/cn/datasets/td500_CN.md 
2. Please edits README.md and README_CN.md [Datasets](https://github.com/mindspore-lab/mindocr/blob/main/README.md#datasets) section to show the support for TD500.

2023-05-02 03:25 UTC, Songyuanwei commented
> 1. Please provide TD500 download instructions as mindocr/docs/en/datasets/td500.md and mindocr/docs/cn/datasets/td500_CN.md
> 2. Please edits README.md and README_CN.md [Datasets](https://github.com/mindspore-lab/mindocr/blob/main/README.md#datasets) section to show the support for TD500.

fixed

2023-05-02 08:14 UTC, wtomin approved these changes

2023-05-03 03:47 UTC, merged