Add Rec Seq2seq components ane configure file, change all config files due to interface change
mindspore-lab/mindocr pull request #253
Opened 2023-05-04 03:14 UTC by zhtmike

Thank you for your contribution to the MindOCR repo.
Before submitting this PR, please make sure:

- [x] You have read the [Contributing Guidelines on pull requests](https://github.com/mindspore-lab/mindcv/blob/main/CONTRIBUTING.md)
- [x] Your code builds clean without any errors or warnings
- [x] You are using approved terminology
- [ ] You have added unit tests

## Motivation

(Write your motivation for proposed changes here.)

## Test Plan

(How should this PR be tested? Do you require special setup to run the test or repro the fixed bug?)

## Related Issues and PRs

(Is this PR part of a group of changes? Link the other relevant PRs and Issues here. Use https://help.github.com/en/articles/closing-issues-using-keywords for help on GitHub syntax)

2023-05-04 04:46 UTC, SamitHuang commented on configs/rec/crnn/crnn_resnet34.yaml
> +    columns_indices_for_net: [0] # input indices for network forward func in output_columns
img_path 作为网络输入看起来有些问题

2023-05-04 04:46 UTC, SamitHuang commented on configs/rec/crnn_seq2seq/crnn_seq2seq_resnet34.yaml
> +    columns_indices_for_net: [0, 1] # input indices for network forward func in output_columns
这里不用指定column_indices_for_label?

2023-05-04 04:46 UTC, SamitHuang commented on mindocr/data/transforms/rec_transforms.py
>      print(seq)
这些中间的print是否必要? 如仅调试用，应删去。

2023-05-04 04:46 UTC, SamitHuang commented on mindocr/models/base_model.py
> +    def construct(self, x, y=None):
需要补充说明入参，x和y。并更新mindocr/models/README.md相应的接口描述。

2023-05-04 04:46 UTC, SamitHuang commented on README.md
建议优化命名：
columns_indices_for_net -> net_input_column_index
columns_indices_for_label -> label_column_index
columns_indices_for_meta_data -> meta_data_column_index
另外，meta_data_column_index 应避免手动指定，output_columns中除去net_input_column_index 和 label_column_index部分剩下都是meta data.

2023-05-04 09:26 UTC, zhtmike commented on configs/rec/crnn/crnn_resnet34.yaml
> +    columns_indices_for_net: [0] # input indices for network forward func in output_columns
经确认pred pipeline目前是不会用到num_columns_to_net的，所以这个参数配置已删除。

2023-05-04 09:27 UTC, zhtmike commented on configs/rec/crnn_seq2seq/crnn_seq2seq_resnet34.yaml
> +    columns_indices_for_net: [0, 1] # input indices for network forward func in output_columns
column_indices_for_label如果不提供会 implicitly 用indices = [1]做为label。现已添加。

2023-05-04 09:28 UTC, zhtmike commented on mindocr/data/transforms/rec_transforms.py
>      print(seq)
已删去。

2023-05-04 09:29 UTC, zhtmike commented on README.md
已更新命名。meta_data_column_index已按这逻辑更新。

2023-05-05 02:25 UTC, hadipash requested changes

2023-05-05 02:25 UTC, hadipash commented on tools/train.py
> -        ema=ema,
lost `ema` argument

2023-05-05 02:25 UTC, hadipash commented on mindocr/models/base_model.py
> +    def construct(self, x, y=None):
I wonder how we will deal with the problem if the backbone or neck will require an extra input.

2023-05-05 02:47 UTC, zhtmike commented on mindocr/losses/builder.py
> +from mindspore.nn import CrossEntropyLoss
cleaned.

2023-05-05 02:48 UTC, zhtmike commented on mindocr/utils/callbacks.py
> +                gt = [data[1]]
The rest of the axes will be marked as meta_data.

2023-05-05 02:49 UTC, zhtmike commented on tools/train.py
> -        ema=ema,
fixed.

2023-05-05 02:50 UTC, zhtmike commented on configs/det/dbnet/db_r50_icdar15.yaml
> +    label_column_index: [1, 2] # input indices marked as label
yes, they have default value. net_input_column_index is default to be [0], label_column_index is default to [1]. We can create a PR later to clean the all unecessary settings.

2023-05-05 02:52 UTC, hadipash commented on mindocr/utils/callbacks.py
> +                gt = [data[1]]
Can it be `gt = [data[start_idx:end_idx]]` where `end_idx` is calculated based on `self.meta_data_indices` the same way as `start_idx` does?

2023-05-05 02:55 UTC, zhtmike commented on mindocr/models/base_model.py
> +    def construct(self, x, y=None):
Current we don't support this feature.

2023-05-05 02:56 UTC, hadipash commented on mindocr/utils/callbacks.py
> +                gt = [data[1]]
Can it be `gt = [data[start_idx:end_idx]]` where `end_idx` is calculated based on `self.meta_data_indices` the same way as `start_idx` does?

2023-05-05 02:56 UTC, hadipash approved these changes

2023-05-05 03:14 UTC, hadipash commented on mindocr/utils/callbacks.py
> +                gt = [data[1]]
We can assume that the indices are continuous for the default case, so we can avoid putting default values into config files.

2023-05-05 06:58 UTC, SamitHuang approved these changes
Good job! Some things to be supplemented next 
1.  readme file for crnn_seq2seq.
2.  avoid setting meta_data_indices as input for simplicity, this can be inferred by set(all_indices) - set(input_indices) - set(label_indices).

2023-05-05 07:06 UTC, merged